### ISSUE TITLE
Replace field injection with constructor injection

### ISSUE THREAD

**Issue by sergejsvisockis** [joejoe2/spring-chat#8]
Due to the fact that having field injection is quite harmful and unpredictable, it's required to replace any occurrence of field injection with constructor-based injection instead.

All the reasons are mentioned in the following article - https://www.baeldung.com/java-spring-field-injection-cons

These are applicable to any Spring-based project.

**Comment by joejoe2** [comment]
resolved in c9964bad345517a46a6e348528708841b063b358

**Comment by sergejsvisockis** [comment]
@joejoe2 It's not resolved.

Fields should be exactly `private` and `final` also dependencies from one Spring bean should never be used in another one. Otherwise, it becomes coupled.

**Comment by sergejsvisockis** [comment]
It's totally fine to inject the same bean into several other beans.
